# .github/workflows/deploy.yml

name: CI/CD for Discord Bot

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    # This job runs on our self-hosted runner
    runs-on: self-hosted

    steps:
      - name: 1. Check out the repository
        uses: actions/checkout@v4

      - name: 2. Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 3. Build the Docker image
        run: |
          docker build -t mellowhrbot-image:${{ github.sha }} .
          docker tag mellowhrbot-image:${{ github.sha }} mellowhrbot-image:latest

      - name: 4. Deploy the new container
        run: |
          # Stop and remove the old container if it exists
          docker stop mellowhrbot || true
          docker rm mellowhrbot || true

          # Run the new container from the 'latest' image
          docker run -d \
            --name mellowhrbot \
            --restart always \
            -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
            -e CLIENT_ID=${{ secrets.CLIENT_ID }} \
            -e MONGO_URI=${{ secrets.MONGO_URI }} \
            mellowhrbot-image:latest
